using '../main.bicep'

param environmentName        = 'prod'
param location               = 'eastus'
param appResourceGroup       = 'theragraf-rg'
param cognitiveResourceGroup = 'Default-Web-EastUS'
param functionAppName        = 'theragraf-functions'
param openAiDeploymentName   = 'gpt-4o-mini'
param openAiAccountName      = 'theragraf-oai'
param languageAccountName    = 'theragraf-language'
param storageAccountName     = 'theragrafstorage'
