using '../main.bicep'

param environmentName        = 'prod'
param location               = 'eastus'
param appResourceGroup       = 'theragraf-rg'
param cognitiveResourceGroup = 'Default-Web-EastUS'
param functionAppName        = 'theragraf-functions'
param openAiDeploymentName   = 'gpt-4o-mini'
param openAiAccountName      = 'theragraf-oai'
param languageAccountName    = 'theragraf-language'
param storageAccountName     = 'theragrafstorage'
param tenantId               = '9525f140-7768-4f65-8ebb-54bd5151f7cb'
param apiClientId            = 'd84a7ccd-aaa1-4adf-8211-7c03fa3d319a'
param cosmosAccountName      = 'theragraf-cosmos'
